CREATE TABLE IF NOT EXISTS wa_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  session_name VARCHAR(80) NOT NULL UNIQUE,
  status ENUM('created','qr_pending','connected','disconnected','blocked','error') NOT NULL DEFAULT 'created',
  phone_jid VARCHAR(120) NULL, phone_label VARCHAR(160) NULL, last_error VARCHAR(1000) NULL,
  last_seen_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wa_channels (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  channel_jid VARCHAR(180) NOT NULL UNIQUE, name VARCHAR(255) NULL, enabled TINYINT(1) NOT NULL DEFAULT 1,
  publish_mode ENUM('off','dry_run','active') NOT NULL DEFAULT 'dry_run', content_profile VARCHAR(80) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wa_control_chats (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  chat_jid VARCHAR(180) NOT NULL UNIQUE, name VARCHAR(255) NULL, enabled TINYINT(1) NOT NULL DEFAULT 1,
  active_channel_jid VARCHAR(180) NULL, interval_minutes INT UNSIGNED NOT NULL DEFAULT 90,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wa_channel_queue (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  channel_jid VARCHAR(180) NOT NULL, source_chat_jid VARCHAR(180) NOT NULL, source_message_id VARCHAR(180) NULL, creator_jid VARCHAR(180) NULL,
  content_type ENUM('text','image','video','document') NOT NULL DEFAULT 'text', text_content TEXT NULL, media_path VARCHAR(1000) NULL, mime_type VARCHAR(160) NULL,
  status ENUM('queued','publishing','published','failed','cancelled') NOT NULL DEFAULT 'queued', scheduled_at DATETIME NOT NULL, published_at DATETIME NULL,
  whatsapp_message_id VARCHAR(180) NULL, error_text VARCHAR(1000) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_wa_channel_queue_source (source_chat_jid, source_message_id), INDEX idx_wa_channel_queue_due (status, scheduled_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wa_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, user_jid VARCHAR(160) NOT NULL UNIQUE, display_name VARCHAR(255) NULL,
  first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, last_seen_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wa_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, message_id VARCHAR(180) NOT NULL, chat_jid VARCHAR(180) NOT NULL, sender_jid VARCHAR(180) NULL,
  message_type VARCHAR(60) NULL, text_preview VARCHAR(1000) NULL, contains_link TINYINT(1) NOT NULL DEFAULT 0, media_kind VARCHAR(60) NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_wa_message_chat_id (chat_jid, message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS wa_actions_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, action_key VARCHAR(120) NOT NULL,
  mode ENUM('dry_run','executed','blocked','failed') NOT NULL DEFAULT 'dry_run', group_jid VARCHAR(180) NULL, target_user_jid VARCHAR(180) NULL,
  message_id VARCHAR(180) NULL, reason VARCHAR(500) NULL, details_json JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
