CREATE TABLE IF NOT EXISTS wa_group_welcome_state (
  group_jid VARCHAR(64) PRIMARY KEY,
  joined_since_last_message INT NOT NULL DEFAULT 0,
  total_joined INT NOT NULL DEFAULT 0,
  last_message_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
